// THIS FILE WAS GENERATED BY A TOOL, DO NOT EDIT!

package main

import (
	"github.com/lxn/walk"
)

type dialogUI struct {
	groupBox     *walk.GroupBox
	tableView    *walk.TableView
	frame        *walk.Composite
	pushButton_5 *walk.PushButton
	pushButton   *walk.PushButton
	pushButton_2 *walk.PushButton
	groupBox_2   *walk.GroupBox
	tableView_2  *walk.TableView
	frame_2      *walk.Composite
	pushButton_6 *walk.PushButton
	pushButton_3 *walk.PushButton
	pushButton_4 *walk.PushButton
	frame_3      *walk.Composite
	pushButton_8 *walk.PushButton
	pushButton_7 *walk.PushButton
}

func (w *EnvSettingDialog) init(owner walk.RootWidget) (err error) {
	if w.Dialog, err = walk.NewDialog(owner); err != nil {
		return err
	}

	succeeded := false
	defer func() {
		if !succeeded {
			w.Dispose()
		}
	}()

	var font *walk.Font
	if font == nil {
		font = nil
	}

	w.SetName("Dialog")
	if err := w.SetClientSize(walk.Size{481, 490}); err != nil {
		return err
	}
	if err := w.SetTitle(`Dialog`); err != nil {
		return err
	}
	if err := w.SetMinMaxSize(walk.Size{0, 0}, walk.Size{16777215, 2000}); err != nil {
		return err
	}
	verticalLayout := walk.NewVBoxLayout()
	if err := w.SetLayout(verticalLayout); err != nil {
		return err
	}
	if err := verticalLayout.SetMargins(walk.Margins{9, 9, 9, 9}); err != nil {
		return err
	}
	if err := verticalLayout.SetSpacing(6); err != nil {
		return err
	}

	// groupBox
	if w.ui.groupBox, err = walk.NewGroupBox(w); err != nil {
		return err
	}
	w.ui.groupBox.SetName("groupBox")
	if err := w.ui.groupBox.SetTitle(`User Env`); err != nil {
		return err
	}
	verticalLayout_2 := walk.NewVBoxLayout()
	if err := w.ui.groupBox.SetLayout(verticalLayout_2); err != nil {
		return err
	}
	if err := verticalLayout_2.SetMargins(walk.Margins{9, 9, 9, 9}); err != nil {
		return err
	}
	if err := verticalLayout_2.SetSpacing(6); err != nil {
		return err
	}

	// tableView
	if w.ui.tableView, err = walk.NewTableView(w.ui.groupBox); err != nil {
		return err
	}
	w.ui.tableView.SetName("tableView")

	// frame
	if w.ui.frame, err = walk.NewComposite(w.ui.groupBox); err != nil {
		return err
	}
	w.ui.frame.SetName("frame")
	horizontalLayout := walk.NewHBoxLayout()
	if err := w.ui.frame.SetLayout(horizontalLayout); err != nil {
		return err
	}
	if err := horizontalLayout.SetMargins(walk.Margins{9, 9, 9, 9}); err != nil {
		return err
	}
	if err := horizontalLayout.SetSpacing(6); err != nil {
		return err
	}

	// anonymous spacer
	if _, err := walk.NewHSpacer(w.ui.frame); err != nil {
		return err
	}

	// pushButton_5
	if w.ui.pushButton_5, err = walk.NewPushButton(w.ui.frame); err != nil {
		return err
	}
	w.ui.pushButton_5.SetName("pushButton_5")
	if err := w.ui.pushButton_5.SetText(`New`); err != nil {
		return err
	}

	// pushButton
	if w.ui.pushButton, err = walk.NewPushButton(w.ui.frame); err != nil {
		return err
	}
	w.ui.pushButton.SetName("pushButton")
	if err := w.ui.pushButton.SetText(`Delete`); err != nil {
		return err
	}

	// pushButton_2
	if w.ui.pushButton_2, err = walk.NewPushButton(w.ui.frame); err != nil {
		return err
	}
	w.ui.pushButton_2.SetName("pushButton_2")
	if err := w.ui.pushButton_2.SetText(`Edit`); err != nil {
		return err
	}

	// groupBox_2
	if w.ui.groupBox_2, err = walk.NewGroupBox(w); err != nil {
		return err
	}
	w.ui.groupBox_2.SetName("groupBox_2")
	if err := w.ui.groupBox_2.SetTitle(`System Env`); err != nil {
		return err
	}
	verticalLayout_3 := walk.NewVBoxLayout()
	if err := w.ui.groupBox_2.SetLayout(verticalLayout_3); err != nil {
		return err
	}
	if err := verticalLayout_3.SetMargins(walk.Margins{9, 9, 9, 9}); err != nil {
		return err
	}
	if err := verticalLayout_3.SetSpacing(6); err != nil {
		return err
	}

	// tableView_2
	if w.ui.tableView_2, err = walk.NewTableView(w.ui.groupBox_2); err != nil {
		return err
	}
	w.ui.tableView_2.SetName("tableView_2")

	// frame_2
	if w.ui.frame_2, err = walk.NewComposite(w.ui.groupBox_2); err != nil {
		return err
	}
	w.ui.frame_2.SetName("frame_2")
	horizontalLayout_2 := walk.NewHBoxLayout()
	if err := w.ui.frame_2.SetLayout(horizontalLayout_2); err != nil {
		return err
	}
	if err := horizontalLayout_2.SetMargins(walk.Margins{9, 9, 9, 9}); err != nil {
		return err
	}
	if err := horizontalLayout_2.SetSpacing(6); err != nil {
		return err
	}

	// anonymous spacer
	if _, err := walk.NewHSpacer(w.ui.frame_2); err != nil {
		return err
	}

	// pushButton_6
	if w.ui.pushButton_6, err = walk.NewPushButton(w.ui.frame_2); err != nil {
		return err
	}
	w.ui.pushButton_6.SetName("pushButton_6")
	if err := w.ui.pushButton_6.SetText(`New`); err != nil {
		return err
	}

	// pushButton_3
	if w.ui.pushButton_3, err = walk.NewPushButton(w.ui.frame_2); err != nil {
		return err
	}
	w.ui.pushButton_3.SetName("pushButton_3")
	if err := w.ui.pushButton_3.SetText(`Delete`); err != nil {
		return err
	}

	// pushButton_4
	if w.ui.pushButton_4, err = walk.NewPushButton(w.ui.frame_2); err != nil {
		return err
	}
	w.ui.pushButton_4.SetName("pushButton_4")
	if err := w.ui.pushButton_4.SetText(`Edit`); err != nil {
		return err
	}

	// frame_3
	if w.ui.frame_3, err = walk.NewComposite(w); err != nil {
		return err
	}
	w.ui.frame_3.SetName("frame_3")
	horizontalLayout_3 := walk.NewHBoxLayout()
	if err := w.ui.frame_3.SetLayout(horizontalLayout_3); err != nil {
		return err
	}
	if err := horizontalLayout_3.SetMargins(walk.Margins{9, 9, 9, 9}); err != nil {
		return err
	}
	if err := horizontalLayout_3.SetSpacing(6); err != nil {
		return err
	}

	// anonymous spacer
	if _, err := walk.NewHSpacer(w.ui.frame_3); err != nil {
		return err
	}

	// pushButton_8
	if w.ui.pushButton_8, err = walk.NewPushButton(w.ui.frame_3); err != nil {
		return err
	}
	w.ui.pushButton_8.SetName("pushButton_8")
	if err := w.ui.pushButton_8.SetText(`OK`); err != nil {
		return err
	}

	// pushButton_7
	if w.ui.pushButton_7, err = walk.NewPushButton(w.ui.frame_3); err != nil {
		return err
	}
	w.ui.pushButton_7.SetName("pushButton_7")
	if err := w.ui.pushButton_7.SetText(`Cancel`); err != nil {
		return err
	}

	// Tab order

	succeeded = true

	return nil
}
